owner:
  - salesagility

repo:
  - SuiteCRM

members:
  - cameronblaikie
  - CamoMacdonald
  - code-ph0y
  - craigpanton
  - Dillon-Brown
  - e-reeley
  - g-fantini
  - gregsoper
  - gymad
  - jack7anderson7
  - JackBuchanan
  - Jason-Dang
  - JimMackin
  - johnM2401
  - Mac-Rae
  - mattlorimer
  - MikeyJC
  - murdal
  - PedroErnst
  - pgorod
  - samus-aran
  - SuiteBot
  - willrennie

eolBranches:
  - 7.9.x,
  - 7.8.x,
  - hotfix-7.8.x

invalidBranches:
  - master

invalid: >
  Hello and thanks for the contribution! would you be able to rebase this pull request to the hotfix-7.10.x branch?
  we currently don't accept pull requests directly to this branch
  (See [SuiteDocs](https://docs.suitecrm.com/community/contributing-code/bugs) for more information).
eol: >
  Hello and thanks for the contribution! unfortunately this branch is EOL
  (See our [blog post](https://suitecrm.com/7-8-x-end-of-life/) for more information).
invalidIssueTemplate: >
  Hello and thanks for raising this issue! I notice you don't seem to be following the standard issue template. If this is a bug report, would you be able to go back and edit this issue while following the template and including exact replication steps?


  Thanks.
sprintPlanning: >
  Hello Everyone! :wave:


  We are 1 week away from commencing our Sprint. So we would like to take this opportunity to ask for your nominated issues here in this thread so we can assess, refine and coordinate with ourselves (the Core Team) and the community contributors on the upcoming priorities.


  If you are new to this sprint planning then essentially we are asking you, as the users, to post your issues (by referencing the GitHub hash/ID) that you would like to see being tackled. We, the Core Team, will review and select the achievable ones within the sprint and allocate them among ourselves. The others we may label them as Help Wanted which would make them up for grabs by our community code contributors. This process will help encourage ownership of these bugs and their bug fixes. [Find out more of the sprint concept here](https://docs.suitecrm.com/community/nominating-issues-in-sprint-planning) :point_left:


  Sprints are every 2 weeks with the aim to deliver a release every 2 Sprints (monthly).


  Just to re-iterate from previous posts, that the core team do have other tasks that may not be identified in the above sprints and these are usually from our own internal backlog i.e. improving the release process, CI/CD tools, security patches etc so that accounts for some ‘slack’ visible in the public sprints.


  Look forward to your nominations! :writing_hand:
sprintRetrospective: >
  Hello Everyone!


  Welcome to the sprint retrospective, lets break down the previous sprint.


  To Do | In Progress | In Review | Done

  ------------ | ------------- | ------------- | -------------

  SPRINTMETRICS


  Again, to note, that we also tackle a lot of other issues that are high priorities, security patches and internal roadmap tasks


  List of the currently open "Help Wanted" issues:

  HELPWANTED



  Thanks everyone and comment below to start a discussion to improve the open sprint processes & gain feedback +1
  We are planning to open the next Sprint for nominations next week.
