language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
matrix:
  fast_finish: true
sudo: required
dist: trusty
services:
  - mysql

install:
  - composer self-update && composer --version

before_script:
  # configure database
  - mysql -e "CREATE DATABASE automated_tests;"
  - mysql -u root -e "CREATE USER 'automated_tests'@'localhost' IDENTIFIED BY 'automated_tests';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON automated_tests.* TO 'automated_tests'@'localhost';"
  - composer install
script:
  - php tests/install.php
  - ./vendor/bin/codecept run -f unit --debug -vvv
  - cat sugarcrm.log

after_script:
  - cat suitecrm.log
  - cat sugarcrm.log

branches:
  only:
    - master
    - develop
    - /hotfix.*/
    - /feature.*/
    - /fix.*/
    - /staging.*/
