language: php
matrix:
  allow_failures:
    - php: 5.4

  include:
    - php: 5.4 # lowest versions of all dependencies
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
install:
  - composer self-update && composer --version

before_script:
  - mysql -e "CREATE DATABASE automated_tests;"
  - mysql -u root -e "CREATE USER 'automated_tests'@'localhost' IDENTIFIED BY 'automated_tests';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON automated_tests.* TO 'automated_tests'@'localhost';"
  - composer install
script:
  - ./vendor/bin/codecept run -f unit
  - cat ../suitecrm.log
services:
  - mysql
branches:
  only:
    - master
    - hotfix
    - develop
    - /feature.*/
