language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
matrix:
  fast_finish: true
sudo: required
dist: trusty
services:
  - mysql
addons:
  chrome: stable

before_install:
  - whereis google-chrome-stable
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ./chromedriver --url-base=/wd/hub &

install:
  - composer self-update && composer --version

before_script:
  # Set up MySQL
  - mysql -e "CREATE DATABASE automated_tests;"
  - mysql -u root -e "CREATE USER 'automated_tests'@'localhost' IDENTIFIED BY 'automated_tests';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON automated_tests.* TO 'automated_tests'@'localhost';"
  # Install apache - images with PHP 7 or above
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipped"; else sudo apt-get update; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo apt-get install apache2 libapache2-mod-fastcgi; fi
  # Enable php-fpm  - images with PHP 7 or above
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo a2enmod rewrite actions fastcgi alias; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo chown -R travis:travis /var/lib/apache2/fastcgi; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm; fi
  # Configure apache virtual hosts - images with PHP 7 or above
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf; fi
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else sudo service apache2 restart; fi
  # Optimise build by removing x-debug
  - phpenv config-rm xdebug.ini
  # Install composer
  - composer install
  - ./vendor/bin/codecept build

script:
  - \[ -f "config_si.php" \] || cp tests/travis_config_si.php config_si.php
  - php tests/testinstall.php
  - ./vendor/bin/codecept run unit --steps
  # Install OAuth2 demo data
  - mysql -u root -D automated_tests -v -e "source tests/_data/api_data.sql"
  # Install demo user data
  - mysql -u root -D automated_tests -v -e "source tests/_data/demo_users.sql"
  # set the log level to error
  - echo "\$sugar_config['logger']['level']='error';" >> config_override.php
  # Run API functional tests
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else ./vendor/bin/codecept run api --steps -vvv; fi
  # RUN Basic Acceptance test
  - if [[ $(phpenv version-name) =~ ^5\.[0-9]$ ]]; then echo "skipping PHP 5.x Images"; else ./vendor/bin/codecept run tests/acceptance/Core/BasicModuleCest.php --env travis-ci-hub -f; fi

after_script:
  - cat suitecrm.log

branches:
  only:
    - master
    - develop
    - /hotfix.*/
    - /feature.*/
    - /fix.*/
    - /staging.*/
