language: php
os: linux
sudo: required

matrix:
  fast_finish: true
  include:
    - name: "PHP 5.5 / MySQL 5.6"
      php: "5.5"
      dist: trusty
    - name: "PHP 5.6 / MySQL 5.6"
      php: "5.6"
      dist: trusty
    - name: "PHP 7.0 / MySQL 5.7"
      php: "7.0"
      dist: xenial
    - name: "PHP 7.1 / MySQL 5.7"
      php: "7.1"
      dist: xenial

before_script:
  - mysql -e "CREATE DATABASE automated_tests CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
  - mysql -u root -e "CREATE USER 'automated_tests'@'localhost' IDENTIFIED BY 'automated_tests';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON automated_tests.* TO 'automated_tests'@'localhost';"
  - composer self-update
  - composer install --no-interaction
  - \[ -f "config_si.php" \] || cp tests/travis_config_si.php config_si.php
  - php tests/testinstall.php
  # Lint PHP
  - for file in $(git diff --name-status HEAD~1 HEAD | egrep "^[ACMR].*\.php$" | cut -c 3-); do php -l $file; done

script:
  - cd tests
  - ../vendor/bin/phpunit
  - cat ../suitecrm.log
services:
  - mysql
branches:
  only:
    - master
    - develop
    - /hotfix.*/
    - /feature.*/
    - /fix.*/
